# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ main ]
env:
  ARTIFACT_NAME: csye6225-webapp-serverless.zip
  AWS_REGION: us-west-2
  APPLICATION_NAME: deployapp
  APPLICATION_DEPLOY_GROUP: deployGroup
  AWS_ACCESS_KEY_ID: 1
  AWS_SECRET_ACCESS_KEY: 1
jobs:
  lambda-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build with maven
        run: mvn -B package --file pom.xml
      
      - name: package
        run: |
          pwd
          mvn clean install
          pwd
          ls -al target
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAWSGWMIDYWZ5I3IGY
          aws-secret-access-key: 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
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy Artifact to S3
        run: |
          aws s3 cp /home/runner/work/serverless/serverless/target/demo-1.0-SNAPSHOT.jar s3://handlerbucket

      - name: update lambda function
        run: |
          aws lambda update-function-code --function-namevemailFunction --s3-bucket handlerbucket --s3-key demo-0.0.1-SNAPSHOT.jar
